<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="1.0" 
xmlns:xsl="http://www.w3.org/1999/XSL/Transform">

<xsl:param name="host" />
<xsl:param name="host_file" />
<xsl:param name="host_view" />
<xsl:param name="host_download" />
<xsl:param name="user" />
<xsl:param name="hole" />
<xsl:param name="holes" />
<xsl:param name="project" />
<xsl:param name="projects" />
<xsl:param name="geol" />
<xsl:param name="geols" />
<xsl:param name="table" />
<xsl:param name="tables" />
<xsl:param name="options" />
<xsl:param name="version" />
<xsl:param name="image" />
<xsl:param name="dictionary" />
<xsl:param name="css" />
<xsl:param name="script" />
<xsl:param name="url_loca" />

<xsl:template match="/">
<html>
	<head>
		<title>Ground Engineering Data GIS table data</title>
		<xsl:choose>
			<xsl:when test="contains($host,'localhost')">
			<link rel="stylesheet" type="text/css" href="/css/ags_format.css" />
			<script type="text/javascript" src="/js/ags_java.js" />
			</xsl:when>
			<xsl:otherwise>
			<link rel="stylesheet" type="text/css" href="../css/ags_format.css" />
			<script type="text/javascript" src="../js/ags_java.js" />
			</xsl:otherwise>
		</xsl:choose>
		<xsl:if test="string-length($css)>0">
			<link rel="stylesheet" type="text/css" href="/css/ags_format.css">
			<xsl:attribute name="href"><xsl:value-of select="$host_file" /><xsl:value-of select="$css" /></xsl:attribute>
			</link>
		</xsl:if>
		<xsl:if test="string-length($script)>0">
			<script type="text/javascript">
			<xsl:attribute name="src"><xsl:value-of select="$host_file" /><xsl:value-of select="$script" /></xsl:attribute>
			</script>
		</xsl:if>
	</head>
	<body>
		<xsl:comment>
			content generated by ge_data xml stylesheet: ge_xml_tables_v001.xsl
			copywrite AECOM 2019
			author: Simon Thomson (simon.thomson@aecom.com)
			date: 26-12-2019
			parameters passed
			host:<xsl:value-of select="$host" />
			host_download:<xsl:value-of select="$host_download" />
			host_file:<xsl:value-of select="$host_file" />
			host_view:<xsl:value-of select="$host_view" />
			user:<xsl:value-of select="$user" />
			hole:<xsl:value-of select="$hole" />
			holes:<xsl:value-of select="$holes" />
			project:<xsl:value-of select="$project" />
			projects:<xsl:value-of select="$projects" />
			geol:<xsl:value-of select="$geol" />
			geols:<xsl:value-of select="$geols" />
			table:<xsl:value-of select="$table" />
			tables:<xsl:value-of select="$tables" />
			options:<xsl:value-of select="$options" />
			version:<xsl:value-of select="$version" />
			dictionary<xsl:value-of select="$dictionary" />
			image:<xsl:value-of select="$image"/>
			script:<xsl:value-of select="$script" />
			css:<xsl:value-of select="$css" />
		</xsl:comment>
		<xsl:if test="$tables='ge_project' or $tables='' or normalize-space($tables)=''">
		<h2> ge_project table details </h2>
			<table>
				<tr>
				<th>Id</th>
				<th>groupId</th>
				
				<th>name</th>
				<th>description</th>
				<th>keywords</th>
				
				<th>start_date</th>
				<th>end_date</th>
				
				<th>locName</th>
				<th>locAddress</th>
				<th>locPostCode</th>
				<th>locMapReference</th>
				<th>locEast</th>
				<th>locNorth</th>
				<th>locLevel</th>
				<th>datumProjection</th>
				<th>locLatitude</th>
				<th>locLongitude</th>
				<th>locHeight</th>
				<th>details</th>
				
				</tr>
				<xsl:apply-templates select="geXML/group/project | geXML/project | /project |*/project"/>
			</table>
		</xsl:if>
		<xsl:if test="$tables='ge_group' or $tables='' or normalize-space($tables)=''">
		<h2> ge_group table details </h2>
			<table>
				<tr>
				<th>Id</th>
				
				<th>name</th>
				<th>description</th>
				<th>keywords</th>
				
				<th>start_date</th>
				<th>end_date</th>
				
				<th>locName</th>
				<th>locAddress</th>
				<th>locPostCode</th>
				<th>locMapReference</th>
				<th>locEast</th>
				<th>locNorth</th>
				<th>locLevel</th>
				<th>datumProjection</th>
				<th>locLatitude</th>
				<th>locLongitude</th>
				<th>locHeight</th>
				<th>details</th>
				</tr>
				<xsl:apply-templates select="geXML/group | /group | */group"/>
			</table>
		</xsl:if>
		<xsl:if test="$tables='ge_data' or $tables='' or normalize-space($tables)=''">
		<h2> ge_data table details </h2>
			<table>
				<tr>
				<th>Id</th>
				<th>projectId</th>
				
				<th>locName</th>
				<th>locAddress</th>
				<th>locPostCode</th>
				<th>locMapReference</th>
				<th>locEast</th>
				<th>locNorth</th>
				<th>locLevel</th>
				<th>datumProjection</th>
				<th>locLatitude</th>
				<th>locLongitude</th>
				<th>locHeight</th>
				
				<th>filename</th>
				<th>filesize</th>
				<th>fileext</th>
				<th>filetype</th>
				<th>description</th>
				<th>keywords</th>
				
				<th>cstatus</th>
				<th>pstatus</th>
				<th>qstatus</th>
				<th>version</th>
				<th>vstatus</th>
				
				<th>view</th>
				<th>download</th>
				</tr>
				<xsl:apply-templates select="geXML/group/project/data | geXML/project/data | /project/data | /data |*/data"/>
			</table>
		</xsl:if>
	</body>
</html> 
</xsl:template>
<xsl:template match="group">
	<tr>
		<td><xsl:value-of select="id"/></td>
		
		<td><xsl:value-of select="name"/></td>
		<td><xsl:value-of select="description"/></td>
		<td><xsl:value-of select="keywords"/></td>
		
		<td><xsl:value-of select="locName"/></td>
		<td><xsl:value-of select="locAddress"/></td>
		<td><xsl:value-of select="locPostCode"/></td>
		<td><xsl:value-of select="locMapReference"/></td>
		<td><xsl:value-of select="locEast"/></td>
		<td><xsl:value-of select="locNorth"/></td>
		<td><xsl:value-of select="locGL"/></td>
		<td><xsl:value-of select="datumProjection"/></td>
		<td><xsl:value-of select="locLatitude"/></td>
		<td><xsl:value-of select="locLongitude"/></td>
		<td><xsl:value-of select="locHeight"/></td>
		<td>
		<a>
				<xsl:attribute name="href">
				<xsl:choose>
					<xsl:when test="string-length(homepageId)>0">
						<xsl:value-of select="$host_view"/><xsl:value-of select="homepageId"/>
					</xsl:when>
					<xsl:otherwise>
						<xsl:value-of select="$host"/>/Group/Details?Id=<xsl:value-of select="Id"/>
					</xsl:otherwise>
				</xsl:choose>
				</xsl:attribute>Details
		</a>
		</td>
	</tr>
</xsl:template>
<xsl:template match="project">
	<tr>
		<td><xsl:value-of select="id"/></td>
		<td><xsl:value-of select="groupId"/></td>
		
		<td><xsl:value-of select="name"/></td>
		<td><xsl:value-of select="description"/></td>
		<td><xsl:value-of select="keywords"/></td>
		
		<td><xsl:value-of select="locName"/></td>
		<td><xsl:value-of select="locAddress"/></td>
		<td><xsl:value-of select="locPostCode"/></td>
		<td><xsl:value-of select="locMapReference"/></td>
		<td><xsl:value-of select="locEast"/></td>
		<td><xsl:value-of select="locNorth"/></td>
		<td><xsl:value-of select="locGL"/></td>
		<td><xsl:value-of select="datumProjection"/></td>
		<td><xsl:value-of select="locLatitude"/></td>
		<td><xsl:value-of select="locLongitude"/></td>
		<td><xsl:value-of select="locHeight"/></td>
		<td>
		<a>
				<xsl:attribute name="href">
				<xsl:choose>
					<xsl:when test="string-length(homepageId)>0">
						<xsl:value-of select="$host_view"/><xsl:value-of select="homepageId"/>
					</xsl:when>
					<xsl:otherwise>
						<xsl:value-of select="$host"/>/Project/Details?Id=<xsl:value-of select="Id"/>
					</xsl:otherwise>
				</xsl:choose>
				</xsl:attribute>Details
		</a>
		</td>
	</tr>
</xsl:template>
<xsl:template match="data">
	<tr>
		<td><xsl:value-of select="id"/></td>
		<td><xsl:value-of select="projectid"/></td>
		
		<td><xsl:value-of select="locName"/></td>
		<td><xsl:value-of select="locAddress"/></td>
		<td><xsl:value-of select="locPostCode"/></td>
		<td><xsl:value-of select="locMapReference"/></td>
		<td><xsl:value-of select="locEast"/></td>
		<td><xsl:value-of select="locNorth"/></td>
		<td><xsl:value-of select="locGL"/></td>
		<td><xsl:value-of select="datumProjection"/></td>
		<td><xsl:value-of select="locLatitude"/></td>
		<td><xsl:value-of select="locLongitude"/></td>
		<td><xsl:value-of select="locHeight"/></td>
		
		<td><xsl:value-of select="filename"/></td>
		<td><xsl:value-of select="filesize"/></td>
		<td><xsl:value-of select="fileext"/></td>
		<td><xsl:value-of select="filetype"/></td>
		<td><xsl:value-of select="description"/></td>
		<td><xsl:value-of select="keywords"/></td>
		
		<td><xsl:value-of select="cstatus"/></td>
		<td><xsl:value-of select="pstatus"/></td>
		<td><xsl:value-of select="qstatus"/></td>
		<td><xsl:value-of select="version"/></td>
		<td><xsl:value-of select="vstatus"/></td>
		<td><a>
					<xsl:attribute name="href">
					<xsl:value-of select="$host_file"/><xsl:value-of select="Id"/>
					</xsl:attribute>View
		</a></td>
		<td><a>
				<xsl:attribute name="href">
				<xsl:value-of select="$host_download"/><xsl:value-of select="Id"/>
				</xsl:attribute>Download
		</a></td>
	</tr>
</xsl:template>
</xsl:stylesheet>